## PokedexData / CódiceData — Base de datos de las 19 criaturas NEXUS Gen 01
## Todas las funciones son estáticas. Se usa vía preload:
##   const PokedexData = preload("res://codigo/datos/pokedex_data.gd")
## IDs: 1001-1019 según CLAUDE.md
## Terminología: "Esencia" (tipo), "Códice" (registro), "Tonal" (criatura)

# ── Colores de Esencias (tipos) ───────────────────────────────────────────────
static var _type_colors: Dictionary = {
	"Normal":   Color(0.66, 0.65, 0.48),
	"Fire":     Color(0.94, 0.50, 0.18),
	"Water":    Color(0.42, 0.56, 0.90),
	"Grass":    Color(0.47, 0.73, 0.34),
	"Electric": Color(0.97, 0.82, 0.17),
	"Ice":      Color(0.58, 0.85, 0.85),
	"Fighting": Color(0.76, 0.19, 0.23),
	"Poison":   Color(0.63, 0.32, 0.67),
	"Ground":   Color(0.89, 0.76, 0.41),
	"Flying":   Color(0.66, 0.56, 0.90),
	"Psychic":  Color(0.97, 0.35, 0.53),
	"Bug":      Color(0.66, 0.73, 0.11),
	"Rock":     Color(0.72, 0.63, 0.23),
	"Ghost":    Color(0.44, 0.35, 0.60),
	"Dragon":   Color(0.44, 0.24, 0.99),
	"Dark":     Color(0.44, 0.35, 0.28),
	"Steel":    Color(0.72, 0.72, 0.82),
	"Fairy":    Color(0.98, 0.66, 0.78),
	"Veil":     Color(0.80, 0.60, 0.95),
}

# ── Nombres de Esencia en español (para UI) ───────────────────────────────────
static var _type_names_es: Dictionary = {
	"Normal":   "Normal",
	"Fire":     "Fuego",
	"Water":    "Agua",
	"Grass":    "Planta",
	"Electric": "Eléctrico",
	"Ice":      "Hielo",
	"Fighting": "Lucha",
	"Poison":   "Veneno",
	"Ground":   "Tierra",
	"Flying":   "Vuelo",
	"Psychic":  "Psíquico",
	"Bug":      "Bicho",
	"Rock":     "Roca",
	"Ghost":    "Espectro",
	"Dragon":   "Dragón",
	"Dark":     "Sombra",
	"Steel":    "Acero",
	"Fairy":    "Hada",
	"Veil":     "Velo",
}

# ── Catálogo de criaturas ─────────────────────────────────────────────────────
static var _catalogue: Array = [
	{
		"id": 1001, "number": 1, "name": "Embral",
		"type1": "Fire", "type2": "Normal",
		"category": "Brasa viva", "region": "Ashenveil",
		"description": "Un perro de fuego de espíritu ardiente. Su llama arde más brillante cuando está cerca de quienes ama.",
		"height": 0.5, "weight": 6.5,
		"base": {"hp": 45, "atk": 55, "def": 40, "spatk": 45, "spdef": 40, "spd": 65},
		"base_exp": 62, "catch_rate": 45,
		"evolution": [1001, 1002],
		"ability": "Blaze",
	},
	{
		"id": 1002, "number": 2, "name": "Embralcinder",
		"type1": "Fire", "type2": "Dark",
		"category": "Ceniza oscura", "region": "Ashenveil",
		"description": "Cuando Embral evoluciona, su llama se mezcla con la oscuridad. Sus cicatrices brillan en la noche.",
		"height": 0.9, "weight": 18.0,
		"base": {"hp": 70, "atk": 90, "def": 65, "spatk": 70, "spdef": 65, "spd": 95},
		"base_exp": 168, "catch_rate": 45,
		"evolution": [1001, 1002],
		"ability": "Blaze",
	},
	{
		"id": 1003, "number": 3, "name": "Folimp",
		"type1": "Grass", "type2": "",
		"category": "Hada de hojas", "region": "Canopy",
		"description": "Una pequeña hada que danza entre las hojas del bosque. Sus pétalos curan heridas leves.",
		"height": 0.3, "weight": 3.2,
		"base": {"hp": 45, "atk": 35, "def": 50, "spatk": 60, "spdef": 55, "spd": 45},
		"base_exp": 58, "catch_rate": 45,
		"evolution": [1003, 1004],
		"ability": "Overgrow",
	},
	{
		"id": 1004, "number": 4, "name": "Folivian",
		"type1": "Grass", "type2": "Bug",
		"category": "Mariposa del bosque", "region": "Canopy",
		"description": "Sus alas recogen luz solar para potenciar sus ataques de hojas. Protege el bosque de intrusos.",
		"height": 0.8, "weight": 12.0,
		"base": {"hp": 65, "atk": 55, "def": 70, "spatk": 90, "spdef": 75, "spd": 65},
		"base_exp": 162, "catch_rate": 45,
		"evolution": [1003, 1004],
		"ability": "Overgrow",
	},
	{
		"id": 1005, "number": 5, "name": "Larvox",
		"type1": "Bug", "type2": "",
		"category": "Oruga gigante", "region": "Canopy",
		"description": "Una oruga gorda y tranquila. Consume hojas día y noche para preparar su transformación.",
		"height": 0.4, "weight": 9.5,
		"base": {"hp": 50, "atk": 35, "def": 55, "spatk": 25, "spdef": 25, "spd": 15},
		"base_exp": 39, "catch_rate": 255,
		"evolution": [1005],
		"ability": "Shield Dust",
	},
	{
		"id": 1006, "number": 6, "name": "Solmund",
		"type1": "Fire", "type2": "Psychic",
		"category": "Espíritu solar", "region": "Ashenveil",
		"description": "Un espíritu solar que duerme dentro de los volcanes inactivos. Se dice que predice terremotos.",
		"height": 1.2, "weight": 22.0,
		"base": {"hp": 60, "atk": 55, "def": 50, "spatk": 80, "spdef": 60, "spd": 70},
		"base_exp": 120, "catch_rate": 60,
		"evolution": [1006],
		"ability": "Drought",
	},
	{
		"id": 1007, "number": 7, "name": "Crystabel",
		"type1": "Ice", "type2": "Fairy",
		"category": "Hada de cristal", "region": "Crystalspire",
		"description": "Su cuerpo es puro cristal de hielo. Cada movimiento suyo produce un sonido de campanas.",
		"height": 0.6, "weight": 8.0,
		"base": {"hp": 55, "atk": 45, "def": 65, "spatk": 75, "spdef": 70, "spd": 50},
		"base_exp": 105, "catch_rate": 75,
		"evolution": [1007],
		"ability": "Pixilate",
	},
	{
		"id": 1008, "number": 8, "name": "Aquellux",
		"type1": "Water", "type2": "Electric",
		"category": "Anguila eléctrica", "region": "Tidebreak",
		"description": "Una anguila capaz de iluminar pueblos costeros con su carga eléctrica. Los pescadores la respetan.",
		"height": 1.1, "weight": 13.5,
		"base": {"hp": 60, "atk": 70, "def": 50, "spatk": 80, "spdef": 55, "spd": 90},
		"base_exp": 130, "catch_rate": 60,
		"evolution": [1008],
		"ability": "Swift Swim",
	},
	{
		"id": 1009, "number": 9, "name": "Oshenite",
		"type1": "Water", "type2": "Ice",
		"category": "Medusa bioluminiscente", "region": "Tidebreak",
		"description": "Flota a las profundidades iluminando las grietas del océano con un suave resplandor azul.",
		"height": 0.7, "weight": 5.5,
		"base": {"hp": 65, "atk": 40, "def": 60, "spatk": 85, "spdef": 80, "spd": 45},
		"base_exp": 118, "catch_rate": 60,
		"evolution": [1009],
		"ability": "Water Absorb",
	},
	{
		"id": 1010, "number": 10, "name": "Necroveil",
		"type1": "Ghost", "type2": "Dark",
		"category": "Velo espectral", "region": "Duskwall",
		"description": "Un velo ancestral que guarda los secretos de los muertos. Aparece en las festividades del Día de Muertos.",
		"height": 1.5, "weight": 0.5,
		"base": {"hp": 55, "atk": 60, "def": 40, "spatk": 85, "spdef": 60, "spd": 75},
		"base_exp": 135, "catch_rate": 45,
		"evolution": [1010],
		"ability": "Cursed Body",
	},
	{
		"id": 1011, "number": 11, "name": "Glacinth",
		"type1": "Ice", "type2": "Steel",
		"category": "Gólem de cristal", "region": "Crystalspire",
		"description": "Un coloso de cristal y acero formado por siglos de presión glacial. Prácticamente indestructible.",
		"height": 2.2, "weight": 320.0,
		"base": {"hp": 80, "atk": 95, "def": 120, "spatk": 60, "spdef": 100, "spd": 30},
		"base_exp": 210, "catch_rate": 25,
		"evolution": [1011],
		"ability": "Sturdy",
	},
	{
		"id": 1012, "number": 12, "name": "Scarfang",
		"type1": "Dragon", "type2": "Fire",
		"category": "Dragón volcánico", "region": "Scarmouth",
		"description": "Nace de la lava. Sus colmillos pueden atravesar roca sólida y su aliento iguala a un volcán.",
		"height": 1.8, "weight": 85.0,
		"base": {"hp": 75, "atk": 110, "def": 80, "spatk": 90, "spdef": 70, "spd": 85},
		"base_exp": 190, "catch_rate": 25,
		"evolution": [1012],
		"ability": "Mold Breaker",
	},
	{
		"id": 1013, "number": 13, "name": "Bonehound",
		"type1": "Ghost", "type2": "Normal",
		"category": "Perro esquelético", "region": "Duskwall",
		"description": "Un perro guardián del más allá. Lleva flores de cempasúchil en su cuello y cuida las tumbas.",
		"height": 0.8, "weight": 15.0,
		"base": {"hp": 65, "atk": 75, "def": 55, "spatk": 50, "spdef": 55, "spd": 70},
		"base_exp": 128, "catch_rate": 60,
		"evolution": [1013],
		"ability": "Levitate",
	},
	{
		"id": 1014, "number": 14, "name": "Veildark",
		"type1": "Psychic", "type2": "Dark",
		"category": "Ser de sombra", "region": "Veilwatch",
		"description": "Un ser nacido de la intersección entre la mente y la oscuridad. Sus ojos brillan como estrellas.",
		"height": 1.4, "weight": 30.0,
		"base": {"hp": 70, "atk": 65, "def": 60, "spatk": 105, "spdef": 90, "spd": 80},
		"base_exp": 175, "catch_rate": 25,
		"evolution": [1014],
		"ability": "Shadow Shield",
	},
	{
		"id": 1015, "number": 15, "name": "Spidrel",
		"type1": "Bug", "type2": "Poison",
		"category": "Araña del bosque", "region": "Canopy",
		"description": "Teje redes que brillan al amanecer. Su veneno paraliza pero raramente es fatal.",
		"height": 0.5, "weight": 7.0,
		"base": {"hp": 45, "atk": 65, "def": 45, "spatk": 55, "spdef": 45, "spd": 75},
		"base_exp": 95, "catch_rate": 120,
		"evolution": [1015],
		"ability": "Compound Eyes",
	},
	{
		"id": 1016, "number": 16, "name": "Deepfin",
		"type1": "Water", "type2": "Dark",
		"category": "Pez de las profundidades", "region": "Tidebreak",
		"description": "Nunca ha sido visto en la superficie. Sus ojos pueden ver en la oscuridad más absoluta.",
		"height": 1.0, "weight": 20.0,
		"base": {"hp": 60, "atk": 85, "def": 55, "spatk": 65, "spdef": 50, "spd": 80},
		"base_exp": 130, "catch_rate": 45,
		"evolution": [1016],
		"ability": "Intimidate",
	},
	{
		"id": 1017, "number": 17, "name": "Drakpup",
		"type1": "Dragon", "type2": "",
		"category": "Cría de dragón", "region": "Scarmouth",
		"description": "Una cría de dragón torpe pero tenaz. Los guías que la tratan bien ganan su lealtad de por vida.",
		"height": 0.6, "weight": 12.0,
		"base": {"hp": 50, "atk": 60, "def": 45, "spatk": 50, "spdef": 45, "spd": 55},
		"base_exp": 80, "catch_rate": 45,
		"evolution": [1017, 1012],
		"ability": "Shed Skin",
	},
	{
		"id": 1018, "number": 18, "name": "Voltux",
		"type1": "Electric", "type2": "Steel",
		"category": "Gólem de trueno", "region": "Voltpeak",
		"description": "Un gólem construido para conducir relámpagos. Sirve como fuente de energía para ciudades enteras.",
		"height": 2.0, "weight": 280.0,
		"base": {"hp": 70, "atk": 80, "def": 100, "spatk": 90, "spdef": 80, "spd": 40},
		"base_exp": 175, "catch_rate": 25,
		"evolution": [1018],
		"ability": "Motor Drive",
	},
	{
		"id": 1019, "number": 19, "name": "Spectryn",
		"type1": "Ghost", "type2": "Psychic",
		"category": "Fantasma de los Seers", "region": "Duskwall",
		"description": "El fantasma de un vidente antiguo que no pudo cruzar al otro lado. Busca respuestas que nunca llegan.",
		"height": 1.6, "weight": 1.0,
		"base": {"hp": 60, "atk": 50, "def": 55, "spatk": 95, "spdef": 90, "spd": 70},
		"base_exp": 160, "catch_rate": 25,
		"evolution": [1019],
		"ability": "Levitate",
	},
	# ── Nexos del Piélago — sprites en res://Sprites_Nexos/ ──────────────────
	{
		"id": 1020, "number": 20, "name": "Aurora",
		"type1": "Ice", "type2": "Fairy",
		"sprite": "Aurora_fase1",
		"category": "Luz boreal", "region": "Piélago",
		"description": "Una criatura que habita en los picos fríos del Piélago. Su melena brilla con los mismos colores que el cielo nocturno.",
		"height": 0.8, "weight": 12.0,
		"base": {"hp": 55, "atk": 45, "def": 60, "spatk": 80, "spdef": 75, "spd": 65},
		"base_exp": 110, "catch_rate": 60,
		"evolution": [1020],
		"ability": "Snow Cloak",
	},
	{
		"id": 1021, "number": 21, "name": "Axolurk",
		"type1": "Water", "type2": "Poison",
		"sprite": "Axolurk_fase2",
		"category": "Axolote acechante", "region": "Coralia",
		"description": "Se regenera incluso en las peores condiciones. Su piel segrega un veneno que adormece a los depredadores.",
		"height": 0.9, "weight": 16.0,
		"base": {"hp": 70, "atk": 60, "def": 65, "spatk": 55, "spdef": 70, "spd": 55},
		"base_exp": 130, "catch_rate": 60,
		"evolution": [1021],
		"ability": "Regenerator",
	},
	{
		"id": 1022, "number": 22, "name": "Derritol",
		"type1": "Fire", "type2": "",
		"sprite": "Derritol_fase1",
		"category": "Criatura fundida", "region": "Zenera",
		"description": "Vive dentro de grietas volcánicas. Cuando se siente amenazado, su temperatura sube hasta hacer el suelo arder.",
		"height": 0.7, "weight": 9.0,
		"base": {"hp": 50, "atk": 65, "def": 45, "spatk": 55, "spdef": 40, "spd": 70},
		"base_exp": 95, "catch_rate": 90,
		"evolution": [1022],
		"ability": "Blaze",
	},
	{
		"id": 1023, "number": 23, "name": "Florista",
		"type1": "Grass", "type2": "Fairy",
		"sprite": "Florista_Fase2",
		"category": "Guardiana del prado", "region": "Coralia",
		"description": "Una guardiana de los prados en flor. Su aroma atrae mariposas y ahuyenta la tristeza.",
		"height": 1.0, "weight": 14.0,
		"base": {"hp": 65, "atk": 50, "def": 70, "spatk": 85, "spdef": 80, "spd": 60},
		"base_exp": 145, "catch_rate": 45,
		"evolution": [1023],
		"ability": "Flower Veil",
	},
	{
		"id": 1024, "number": 24, "name": "Gorripo",
		"type1": "Normal", "type2": "Fighting",
		"sprite": "Gorripo_fase2",
		"category": "Boxeador callejero", "region": "Piélago",
		"description": "Su gorro es en realidad una coraza endurecida. Los golpes que lanza con la cabeza no tienen precedente entre los nexos de tamaño similar.",
		"height": 1.1, "weight": 38.0,
		"base": {"hp": 80, "atk": 95, "def": 70, "spatk": 50, "spdef": 60, "spd": 65},
		"base_exp": 155, "catch_rate": 60,
		"evolution": [1024],
		"ability": "Iron Fist",
	},
	{
		"id": 1025, "number": 25, "name": "Hollfrost",
		"type1": "Ice", "type2": "Ghost",
		"sprite": "Hollfrost_fase2",
		"category": "Sombra glacial", "region": "Piélago",
		"description": "Merodea por los glaciares en noches sin luna. Los viajeros que lo ven reportan sentir un frío interior que ningún fuego puede calmar.",
		"height": 1.4, "weight": 0.8,
		"base": {"hp": 60, "atk": 55, "def": 70, "spatk": 90, "spdef": 85, "spd": 75},
		"base_exp": 165, "catch_rate": 35,
		"evolution": [1025],
		"ability": "Cursed Body",
	},
	{
		"id": 1026, "number": 26, "name": "Lienx",
		"type1": "Psychic", "type2": "",
		"sprite": "Lienx_Fase2",
		"category": "Lince mental", "region": "Nora",
		"description": "Su mirada penetra los pensamientos más profundos. Se comunica telepáticamente y rara vez vocaliza.",
		"height": 1.2, "weight": 28.0,
		"base": {"hp": 65, "atk": 55, "def": 60, "spatk": 100, "spdef": 90, "spd": 85},
		"base_exp": 170, "catch_rate": 35,
		"evolution": [1026],
		"ability": "Synchronize",
	},
	{
		"id": 1027, "number": 27, "name": "Miauth",
		"type1": "Normal", "type2": "Fairy",
		"sprite": "Miauth_fase1",
		"category": "Felino amigable", "region": "Piélago",
		"description": "Uno de los nexos más comunes en los pueblos del Piélago. Su ronroneo tiene propiedades calmantes sobre el Latido.",
		"height": 0.4, "weight": 4.5,
		"base": {"hp": 50, "atk": 40, "def": 45, "spatk": 55, "spdef": 50, "spd": 65},
		"base_exp": 70, "catch_rate": 150,
		"evolution": [1027],
		"ability": "Cute Charm",
	},
	{
		"id": 1028, "number": 28, "name": "Mordecur",
		"type1": "Poison", "type2": "Dark",
		"sprite": "Mordecur_fase1",
		"category": "Reptil mordedor", "region": "Nora",
		"description": "Sus colmillos inyectan un veneno que confunde los sentidos. Habita en las grietas de las rocas del desierto.",
		"height": 0.6, "weight": 11.0,
		"base": {"hp": 55, "atk": 75, "def": 50, "spatk": 60, "spdef": 45, "spd": 80},
		"base_exp": 105, "catch_rate": 90,
		"evolution": [1028],
		"ability": "Poison Point",
	},
	{
		"id": 1029, "number": 29, "name": "Pectrix",
		"type1": "Rock", "type2": "",
		"sprite": "Pectrix_fase1",
		"category": "Gólem pedregoso", "region": "Zenera",
		"description": "Una criatura rocosa que absorbe los minerales del suelo para reforzar su coraza. Lento pero imposible de ignorar.",
		"height": 0.9, "weight": 65.0,
		"base": {"hp": 65, "atk": 70, "def": 90, "spatk": 35, "spdef": 55, "spd": 25},
		"base_exp": 105, "catch_rate": 90,
		"evolution": [1029],
		"ability": "Sturdy",
	},
	{
		"id": 1030, "number": 30, "name": "Velimal",
		"type1": "Flying", "type2": "Normal",
		"sprite": "Velimal_fase2",
		"category": "Bestia del viento", "region": "Piélago",
		"description": "Vuela a gran velocidad y caza al vuelo. Sus alas producen un sonido que desorienta a sus presas.",
		"height": 1.3, "weight": 22.0,
		"base": {"hp": 70, "atk": 80, "def": 60, "spatk": 55, "spdef": 60, "spd": 95},
		"base_exp": 145, "catch_rate": 60,
		"evolution": [1030],
		"ability": "Keen Eye",
	},
	{
		"id": 1031, "number": 31, "name": "Cascabex",
		"type1": "Fire", "type2": "Ground",
		"sprite": "cand_Cascabex",
		"category": "Serpiente de cascabel", "region": "Nora",
		"description": "El sonido de su cola es una advertencia que los viajeros del desierto aprendieron a respetar. Su mordida puede carbonizar la arena.",
		"height": 1.5, "weight": 30.0,
		"base": {"hp": 65, "atk": 85, "def": 55, "spatk": 70, "spdef": 55, "spd": 75},
		"base_exp": 135, "catch_rate": 60,
		"evolution": [1031],
		"ability": "Sand Veil",
	},
	{
		"id": 1032, "number": 32, "name": "Semillillo",
		"type1": "Grass", "type2": "",
		"sprite": "cand_Semillillo",
		"category": "Semilla andante", "region": "Coralia",
		"description": "Una semilla que decidió caminar. Planta nuevos árboles allá donde va, dejando a su paso un rastro de brotes.",
		"height": 0.3, "weight": 2.5,
		"base": {"hp": 45, "atk": 30, "def": 50, "spatk": 45, "spdef": 55, "spd": 40},
		"base_exp": 55, "catch_rate": 180,
		"evolution": [1032],
		"ability": "Overgrow",
	},
	{
		"id": 1033, "number": 33, "name": "Copalux",
		"type1": "Ghost", "type2": "Fire",
		"sprite": "evo_Copalux_stage3_core",
		"category": "Espíritu del copal", "region": "Levante",
		"description": "Surgido del humo del copal ceremonial, sirve de guía entre mundos. Algunos guías lo ven en momentos de gran vínculo.",
		"height": 1.8, "weight": 0.3,
		"base": {"hp": 70, "atk": 65, "def": 60, "spatk": 105, "spdef": 90, "spd": 80},
		"base_exp": 175, "catch_rate": 20,
		"evolution": [1033],
		"ability": "Flash Fire",
	},
	{
		"id": 1034, "number": 34, "name": "Alacrix",
		"type1": "Flying", "type2": "Electric",
		"sprite": "icon_Alacrix",
		"category": "Ave del relámpago", "region": "Zenera",
		"description": "Un ave que cabalga las tormentas. Sus plumas acumulan tanta carga eléctrica que pueden encender linternas con solo rozarlas.",
		"height": 0.9, "weight": 8.5,
		"base": {"hp": 60, "atk": 70, "def": 50, "spatk": 80, "spdef": 55, "spd": 100},
		"base_exp": 135, "catch_rate": 45,
		"evolution": [1034],
		"ability": "Static",
	},
	{
		"id": 1035, "number": 35, "name": "Calavela",
		"type1": "Ghost", "type2": "Dark",
		"sprite": "icon_Calavela",
		"category": "Cráneo velado", "region": "Levante",
		"description": "Aparece durante las noches de festejo en Levante. Su vela nunca se apaga y su sonrisa nunca cambia.",
		"height": 0.7, "weight": 3.0,
		"base": {"hp": 55, "atk": 65, "def": 45, "spatk": 85, "spdef": 65, "spd": 85},
		"base_exp": 120, "catch_rate": 60,
		"evolution": [1035],
		"ability": "Levitate",
	},
	{
		"id": 1036, "number": 36, "name": "Palohex",
		"type1": "Dark", "type2": "Grass",
		"sprite": "icon_Palohex",
		"category": "Vara maldita", "region": "Coralia",
		"description": "Una rama maldita que camina por sí sola. Sus hechizos enredan a las presas en lianas que crecen al instante.",
		"height": 1.1, "weight": 6.0,
		"base": {"hp": 60, "atk": 75, "def": 55, "spatk": 70, "spdef": 60, "spd": 75},
		"base_exp": 120, "catch_rate": 75,
		"evolution": [1036],
		"ability": "Prankster",
	},
	{
		"id": 1037, "number": 37, "name": "Serphueso",
		"type1": "Poison", "type2": "Ground",
		"sprite": "icon_Serphueso",
		"category": "Serpiente de hueso", "region": "Nora",
		"description": "Sus costillas son visibles a través de la piel translúcida. Usa vibraciones sísmicas para detectar presas bajo la arena.",
		"height": 2.0, "weight": 18.0,
		"base": {"hp": 70, "atk": 80, "def": 65, "spatk": 55, "spdef": 60, "spd": 70},
		"base_exp": 130, "catch_rate": 60,
		"evolution": [1037],
		"ability": "Sand Rush",
	},
	{
		"id": 1038, "number": 38, "name": "Totemix",
		"type1": "Rock", "type2": "Ground",
		"sprite": "icon_Totemix",
		"category": "Tótem viviente", "region": "Nora",
		"description": "Un tótem ancestral que cobró vida. Los pueblos del desierto lo veneran y le ofrecen agua en épocas de sequía.",
		"height": 1.6, "weight": 180.0,
		"base": {"hp": 85, "atk": 80, "def": 110, "spatk": 50, "spdef": 85, "spd": 25},
		"base_exp": 165, "catch_rate": 30,
		"evolution": [1038],
		"ability": "Rock Head",
	},
	{
		"id": 1039, "number": 39, "name": "Jollow",
		"type1": "Ghost", "type2": "Flying",
		"sprite": "jollow_fase1",
		"category": "Espectro alado", "region": "Levante",
		"description": "Un espíritu jovial que acompaña a los viajeros nocturnos. Su risa se oye antes de que sea visible.",
		"height": 0.5, "weight": 0.4,
		"base": {"hp": 45, "atk": 35, "def": 40, "spatk": 60, "spdef": 55, "spd": 75},
		"base_exp": 75, "catch_rate": 120,
		"evolution": [1039],
		"ability": "Levitate",
	},
]

# ── Índice por ID para lookup rápido ──────────────────────────────────────────
static var _by_id: Dictionary = {}

static func _ensure_index() -> void:
	if not _by_id.is_empty():
		return
	for entry in _catalogue:
		_by_id[entry["id"]] = entry

# ── API pública ────────────────────────────────────────────────────────────────

## Lista de todos los IDs (int)
static func get_all_ids() -> Array:
	_ensure_index()
	return _by_id.keys()

## Obtener entrada por ID (int). Devuelve dict vacío si no existe.
static func get_entry(id: int) -> Dictionary:
	_ensure_index()
	return _by_id.get(id, {})

## Catálogo completo (Array de Dictionaries)
static func get_catalogue() -> Array:
	return _catalogue

## Color de Esencia para UI
static func type_color(type_name: String) -> Color:
	return _type_colors.get(type_name, Color(0.7, 0.7, 0.7))

## Nombre de Esencia en español para UI
static func esencia_es(type_name: String) -> String:
	return _type_names_es.get(type_name, type_name)

## Nombre de Esencia formateado con color BBCode para RichTextLabel
static func esencia_bbcode(type_name: String) -> String:
	var col = type_color(type_name)
	var hex = col.to_html(false)
	return "[color=#%s]%s[/color]" % [hex, esencia_es(type_name)]
